language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - docker

install:
  - composer install

before_script:
  - docker run -d --name jaeger
      -e COLLECTOR_ZIPKIN_HTTP_PORT=9411
      -p 5775:5775/udp
      -p 6831:6831/udp
      -p 6832:6832/udp
      -p 5778:5778
      -p 16686:16686
      -p 14268:14268
      -p 9411:9411
      jaegertracing/all-in-one:1.10

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: lint
      php: 7.2
      install:
        - composer require phpstan/phpstan friendsofphp/php-cs-fixer
      before_script: []
      script:
        - vendor/bin/phpstan analyze --no-progress src
        - vendor/bin/php-cs-fixer fix --dry-run --diff
